### ISSUE TITLE
Auto-generate additionalProperties for maps?

### ISSUE THREAD

**Issue by clounie** [Bankdata/gradle-swagger-plugin#12]
Hey again,

Converted to the OpenAPI 3 annotations a while back and it's been great - thanks for keeping this up to date.

I'd like to use additionalProperties to properly display Maps as described here... https://swagger.io/docs/specification/data-models/dictionaries/ ?

Would that be something which could be done here (I'd be willing to do the work on it..) or something more for the swagger-core repository?

**Comment by langecode** [comment]
Thanks for the nice words.

The Gradle plugin is pretty much just scanning for classes and passing the list of classes to Swagger. So I am pretty sure this would have to be handled in the Swagger library but I will look into this. It might be a matter of adding in a Swagger annotation on your map property.
