### ISSUE TITLE
Task should use compile classpath when scanning

### ISSUE THREAD

**Issue by jskovjyskebankdk** [Bankdata/gradle-swagger-plugin#5]
The point of this plugin (as I understand it, or at least as I intend to use it), is to generate the swagger api at compile time.

We normally have web project dependency configurations looking like:

````
dependencies {
    compileOnly "org.slf4j:slf4j-api"
    compileOnly "org.jboss.spec.javax.ejb:jboss-ejb-api_3.1_spec"
    compileOnly "javax.enterprise:cdi-api"
    ...
}
````
This is because these dependencies are provided by the web container at runtime.

But the swaggerGenerate task uses runtime classpath, which means the above are not picked up.

I am not sure if the compile classpath is always suitable (current implementation would suggest not).
But then configuration of which classpath to use would make sense.

**Comment by langecode** [comment]
That is a good point. It has probably been working because the Swagger JAX-RS module is drawing in some of these dependencies with the plugin. I think you are right it would be more proper to actually rely on the compile classpath as this must contain the classes necessary to classload the REST resources.

**Comment by jskovjyskebankdk** [comment]
Nice!

2.0.1? :)

**Comment by langecode** [comment]
Turned out there was more to it than just changing the classpath used in the task. Class loading at its best :-)

2.0.2 coming shortly and seems to work on my test project.

**Comment by langecode** [comment]
Should be solved by release 2.0.2

**Comment by jskovjyskebankdk** [comment]
Thanks for your perseverance :) I will test it as soon as it hits Maven Central.

**Comment by jskovjyskebankdk** [comment]
Looks fine to me!

Cheers
